version: '3.8'

services:
  myapp:
    build: .
    image: tanysiew007/svelte-blessed:latest
    ports:
      - 3000:3000
    networks:
      - svelte

  pb:
    build: ./pb
    ports:
      - "8003:8080"
    environment:
      PB_VERSION: "0.22.12"
    volumes:
      - ./pb/pb_data:/pb/pb_data
    networks:
      - svelte
      # Uncomment if you have local pb_migrations and pb_hooks directories
      # - ./pb_migrations:/pb/pb_migrations
      # - ./pb_hooks:/pb/pb_hooks

networks:
    svelte:
  